- pythongames/RockPaperScissor/rockpaperscissor.py
Added a try-except statement to the script in order to prevent the script from throwing a Value Error and instead prompt asking for an Integer input.
This solves #31
> Update RockPaperScissor game script to prevent the ValueError

- pythongames/RockPaperScissor/README.md
I have updated the ReadMe File for RockPaperScissor game.
I have added the following in the ReadMe file:
~ A brief introduction of the game.
~ Listed the requirement for running the game.
~ Listed few features of the game.
~ Added credits.
> Docs: #44 ReadMe Created For RockPaperScissor

- pythongames/spaceinvaders/README.md
Issue #43 
Adding README.md file for the Spaceinvaders game.
- edit/README
@SubstantialCattle5
> Create A Readme ( SpaceInvaders - Python ) #43

- pythongames/spaceinvaders/main.py
#36 Resolve the bug. set the value of bullet_state=NULL after game over.
> Game Over ( SpaceInvaders - Python ) #36

- jsgames/tictactoe/main.js
#32 issue resolved by adding checkpoint
> Game Ends ( TicTacToe - JS ) #32

- pythongames/snake/README.md
Issue #51 
@mekken2 @Subham-Panda  @ashikka @nimishjn @3xpl0itk1t 
Docs: README.md has been added with,
-Introduction
-Installation
-Requirements
-Features etc...
> Create A Readme ( Snake - Python ) #51

- pythongames/snake/snake.py
@3xpl0itk1t Added time limit to snake game #39
> Time Limit ( Snake - Python ) #39

- pythongames/snake/snake.py
@mekken2 @Subham-Panda @ashikka @nimishjn @3xpl0itk1t 
fix: When both W and S are pressed together the games stops,
Since W and S are "UP" and "DOWN", the opposite directions cannot be pressed together, To remove this error a simple if statement is added when changing thee direction, to check if the current direction is either "UP" or "DOWN"
> Movement ( Snake - Python ) #28

- pythongames/spaceinvaders/main.py
> [BUG] Shooting ( SpaceInvaders - Python ) #35

- javagames/bowling/Bowling.java
> [BUG] Roll ( Bowling - Java ) #30

- pythongames/snake/snake.py
@mekken2 @Subham-Panda @ashikka @nimishjn @3xpl0itk1t 
feat: New Levels feature is added
For every 10 points, the player collects, the level increases,
For every new level, the background and the snake's body color changes
> Level ( Snake - Python ) #40

- javagames/hangmangame/Hangman.java
> [BUG] Input ( Hangman - Java ) #29

- jsgames/tictactoe/main.js
> Second Move ( TicTacToe - JS ) #33

- javagames/hangmangame/README.md
I have added a ReadMe file for Hangman - Java game.
It includes the following:
~ Introduction
~ Game Rules
~ Requirements
~ Installation
~ Features
~ Contribution
~ Credits
~ License
> Docs: #49 ReadMe Created (Hangman - Java)

- pythongames/spaceinvaders/main.py
@3xpl0itk1t resolve the issue so when aliens change speed user will get a warning about that. #34
> Speed Increase ( SpaceInvaders - Python ) #34

- javagames/hangmangame/Hangman.java
=> The program will now ask the user to choose the level
=> Levels are based on number of letters in the word
Issue link- [Levels ( Hangman - Java ) #37](https://github.com/csivitu/ArcadeGames/issues/37)
@3xpl0itk1t @SubstantialCattle5
> [Enhancement] Levels ( Hangman - Java ) #37

- pythongames/snake/snake.py
@3xpl0itk1t , added timelimit for each point, timelimit = 7 secs
> [Feat] : Adding timelimit for each point (snake - python) #89

- jsgames/tictactoe/main.js
Created a new feature to play 2 player Tic Tac Toe using JS.
> 2 player commit

- README.md
Hey @3xpl0itk1t 
I had made all the changes for issue #99  hope you will like it.
> Added contributors details with profile pics.

- csharpgames/README.md
I made a simple readme for the checkers game in csharp . Please check
> feat : added a description for checkers game

- jsgames/sliding_puzzle/index.html
A simple game where you have to order numbers from 1 to 8 , a lot of improvements can be made. Related to #115
> Feat#115 Add sliding_puzzle javascript game

- pythongames/blackjack/blackjack.py
Just made a blackjack game in python do check it out!
> feat : blackjack game in python

- pythongames/Asteroids/README.md
> added README.md for Asteroids.

- pythongames/blackjack/README.md
> added README.md for Blackjack.

- pythongames/Pacman/README.md
> added README.md for Pacman.

- javagames/Bombardment/Bombardment.java
- javagames/Bombardment/BombardmentGame.java
Hey guys i made a game on Java a while back please check and merge if it fits your criteria thank you :)
> Bombardment (Game on Java)

- pythongames/queen/.flake8
- pythongames/queen/queen.py
I made  a queen game so that i can contribute and be the part of Hacktoberfest . Hope you like it :)
> feat : made a queen game

- javagames/towers/Tower.java
- pythongames/queen/.flake8
- pythongames/queen/queen.py
Hey guys i made a game called towers as a fun project for my java studies . Hope you like it :)
> feat : Towers a game in java

- javagames/towers/README.md
- pythongames/queen/README.md
I have created a readme file for the game tower, as per you requested. Thank you :)
> Feat: made a readme file 

- javagames/towers/README.md
- pythongames/queen/README.md
I made a readme file for the game Queen, as you requested. Thank you :)
> Feat: made a readme file

- javagames/Bombardment/README.md
Created a readme file for the game bombardment  as requested . thankyou :)
> feat : added a readme for bombardment

- jsgames/horserace/README.md
created a readme file , for the game horserace(a java script game), as per your request , please check and approve :))
> feat : made a readme for horserace

- javagames/HighIQ/HighIQ.java
- javagames/HighIQ/HighIQGame.java
High guys i made a game in java a while hope you guys like it ....
> feat  : made HighIQ in java

- javagames/HighIQ/README.md
I made the readme you requested me to make
> feat : made a readme for HighIQ

- jsgames/pacman_game/app.js
- jsgames/pacman_game/index.html
- jsgames/pacman_game/style.css
Hi! I've added pacman game coded using JavaScript to the repo. I followed contributing guidelines to the best of my knowledge. Thank you.
> feat: Add Pacman Javascript

- htmlgames/piano tiles/index.html
- htmlgames/piano tiles/script.js
- htmlgames/piano tiles/styles.css
I made a piano tiles game using html css and js please review . Thank you
> feat: made a piano tiles game

- pythongames/Hammurabi/Hamurabi.py
Made a game of hammurabi using python hope you guys like it
> feat : added hammurabi in python

- jsgames/Hangman/README.md
A word-guessing game in which one player chooses a word that the other player must guess by giving each letter of the word is played. For each incorrect guess, a stick figure depicting a hanged man is drawn in part.
> Create a README.md Hangman

- pythongames/tower/README.md
Tower is a strategy game subgenre in which the goal is to defend a player's territory or possessions by obstructing enemy attackers or preventing enemies from reaching exits, which is usually accomplished by placing defensive structures on or along their path of attack.
> Create README.md tower
